In [ ]:
import pandas as pd

In [ ]:
stock_df = pd.read_csv(
    "/content/stock_cleaned.csv",
    parse_dates=["Date"]
)

stock_df.head()

  Company       Date    Close     Volume     Open     High      Low
0    AAPL 2013-07-18  15.4199  218632537  15.4779  15.5311  15.3789
1    AAPL 2013-07-19  15.1768  268548901  15.4679  15.4993  15.1554
2    AAPL 2013-07-22  15.2254  207648981  15.3379  15.3482  15.1953
3    AAPL 2013-07-23  14.9639  354477618  15.2143  15.2486  14.9539
4    AAPL 2013-07-24  15.7325  591624923  15.6761  15.8782  15.5450

In [ ]:
for lag in [1, 5, 21]:
    stock_df[f"lag_{lag}"] = stock_df["Close"].shift(lag)

for span in [12, 26]:
    stock_df[f"ema_{span}"] = stock_df["Close"].ewm(span=span, adjust=False).mean()

stock_df["macd"] = stock_df["ema_12"] - stock_df["ema_26"]
stock_df["momentum_10"]   = stock_df["Close"].pct_change(10)
stock_df["volatility_21"] = stock_df["Close"].rolling(21).std()

stock_df["volume_change"]  = stock_df["Volume"].pct_change()
stock_df["volume_ma_7"]    = stock_df["Volume"].rolling(7).mean()
stock_df["relative_volume"] = stock_df["Volume"] / stock_df["volume_ma_7"]

stock_df["daily_range"] = (stock_df["High"] - stock_df["Low"]) / stock_df["Close"]
stock_df["oc_return"] = (stock_df["Close"] - stock_df["Open"]) / stock_df["Open"]

In [ ]:
stock_df.head()

,Company,Date,Close,Volume,Open,High,Low,lag_1,lag_5,lag_21,ema_12,ema_26,macd,momentum_10,volatility_21,volume_change,volume_ma_7,relative_volume,daily_range,oc_return
0,AAPL,2013-07-18,15.4199,218632537,15.4779,15.5311,15.3789,NaN,NaN,NaN,15.419900,15.419900,0.000000,NaN,NaN,NaN,NaN,NaN,0.009870,-0.003747
1,AAPL,2013-07-19,15.1768,268548901,15.4679,15.4993,15.1554,15.4199,NaN,NaN,15.382500,15.401893,-0.019393,NaN,NaN,0.228312,NaN,NaN,0.022660,-0.018820
2,AAPL,2013-07-22,15.2254,207648981,15.3379,15.3482,15.1953,15.1768,NaN,NaN,15.358331,15.388819,-0.030488,NaN,NaN,-0.226774,NaN,NaN,0.010042,-0.007335
3,AAPL,2013-07-23,14.9639,354477618,15.2143,15.2486,14.9539,15.2254,NaN,NaN,15.297649,15.357344,-0.059694,NaN,NaN,0.707100,NaN,NaN,0.019694,-0.016458
4,AAPL,2013-07-24,15.7325,591624923,15.6761,15.8782,15.5450,14.9639,NaN,NaN,15.364549,15.385133,-0.020584,NaN,NaN,0.669005,NaN,NaN,0.021179,0.003598

In [ ]:
stock_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25160 entries, 0 to 25159
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Company          25160 non-null  object
 1   Date             25160 non-null  datetime64[ns]
 2   Close            25160 non-null  float64
 3   Volume           25160 non-null  int64
 4   Open             25160 non-null  float64
 5   High             25160 non-null  float64
 6   Low              25160 non-null  float64
 7   lag_1            25159 non-null  float64
 8   lag_5            25155 non-null  float64
 9   lag_21           25139 non-null  float64
 10  ema_12           25160 non-null  float64
 11  ema_26           25160 non-null  float64
 12  macd             25160 non-null  float64
 13  momentum_10      25150 non-null  float64
 14  volatility_21    25140 non-null  float64
 15  volume_change    25159 non-null  float64
 16  volume_ma_7      25154 non-null  float64
 17  relative_volume  25154 non-null  float64
 18  daily_range      25160 non-null  float64
 19  oc_return        25160 non-null  float64
dtypes: datetime64[ns](1), float64(17), int64(1), object(1)
memory usage: 3.8+ MB

In [ ]:
stock_df.describe()

,Date,Close,Volume,Open,High,Low,lag_1,lag_5,lag_21,ema_12,ema_26,macd,momentum_10,volatility_21,volume_change,volume_ma_7,relative_volume,daily_range,oc_return
count,25160,25160.000000,2.516000e+04,25160.000000,25160.000000,25160.000000,25159.000000,25155.000000,25139.000000,25160.000000,25160.000000,25160.000000,25150.000000,25140.000000,25159.000000,2.515400e+04,25154.000000,25160.000000,25160.000000
mean,2018-07-15 16:11:49.697933056,102.455878,5.131764e+07,102.430761,103.829305,101.006112,102.448408,102.420928,102.318200,102.399389,102.334784,0.064605,0.008339,4.448550,0.071641,5.128222e+07,1.007897,0.026185,0.000461
min,2013-07-18 00:00:00,1.620000,1.143952e+06,1.620000,1.690000,1.610000,1.620000,1.620000,1.620000,1.745111,1.786735,-98.542195,-0.980806,0.027732,-0.809122,1.830252e+06,0.201325,0.003653,-0.168410
25%,2016-01-14 18:00:00,36.567500,1.200394e+07,36.507500,36.890000,36.128000,36.565000,36.560000,36.540000,37.081486,37.490455,-0.464312,-0.027383,0.829856,-0.193228,1.268642e+07,0.791954,0.014321,-0.008636
50%,2018-07-16 12:00:00,65.680000,2.672083e+07,65.650000,66.486900,64.915500,65.680000,65.660000,65.584300,65.914447,65.946365,0.251164,0.009788,1.854225,-0.020280,2.719066e+07,0.942136,0.021236,0.000376
75%,2021-01-13 06:00:00,134.235025,6.857269e+07,134.320000,136.233525,132.660000,134.210000,134.185000,133.999500,134.783163,134.991905,1.217168,0.046479,4.892044,0.212818,7.163088e+07,1.136390,0.032391,0.009464
max,2023-07-17 00:00:00,691.690000,1.065209e+09,692.350000,700.989400,686.090000,691.690000,691.690000,691.690000,674.477510,661.961721,38.067931,0.658836,194.531174,31.491509,5.842564e+08,5.800918,0.440815,0.250784
std,NaN,101.991372,6.399143e+07,101.996115,103.529523,100.399743,101.986517,101.971321,101.922019,101.551822,101.060103,5.942462,0.091096,9.179805,0.502691,5.874933e+07,0.352100,0.018085,0.019042

In [ ]:
stock_df.to_csv('stock_features.csv', index=False)