## Import libraries

In [ ]:
import pandas as pd

## Load data

In [ ]:
DATA_PATH = "/content/stock_market.csv"
stock_df = pd.read_csv(DATA_PATH)
stock_df.head()

  Company        Date Close/Last    Volume     Open       High      Low
0    AAPL  07/17/2023    $193.99  50520160  $191.90    $194.32  $191.81
1    AAPL  07/14/2023    $190.69  41616240  $190.23  $191.1799  $189.63
2    AAPL  07/13/2023    $190.54  41342340  $190.50    $191.19  $189.78
3    AAPL  07-12-2023    $189.77  60750250  $189.68    $191.70  $188.47
4    AAPL  07-11-2023    $188.08  46638120  $189.16    $189.30  $186.60

## Assess data

In [ ]:
stock_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25160 entries, 0 to 25159
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Company     25160 non-null  object
 1   Date        25160 non-null  object
 2   Close/Last  25160 non-null  object
 3   Volume      25160 non-null  int64
 4   Open        25160 non-null  object
 5   High        25160 non-null  object
 6   Low         25160 non-null  object
dtypes: int64(1), object(6)
memory usage: 1.3+ MB

In [ ]:
print('Duplicated rows: ', stock_df.duplicated().sum())

Duplicated rows:  0

In [ ]:
stock_df['Company'].value_counts()

Company
AAPL    2516
SBUX    2516
MSFT    2516
CSCO    2516
QCOM    2516
META    2516
AMZN    2516
TSLA    2516
AMD     2516
NFLX    2516
Name: count, dtype: int64

## Data Wrangling

### Convert prices to float

In [ ]:
price_cols = ['Close/Last', 'Open', 'High', 'Low']
for col in price_cols:
  stock_df[col] = stock_df[col].apply(lambda x: float(str(x).replace("$", "")))

### Convert date to datetime

In [ ]:
stock_df['Date'] = stock_df["Date"].apply(lambda x: x.replace("-", "/"))
stock_df['Date'] = pd.to_datetime(stock_df['Date'], format="%m/%d/%Y")

### Rename and sort

In [ ]:
stock_df = stock_df.rename(columns={"Close/Last": "Close"})

In [ ]:
stock_df = stock_df.sort_values(["Company", "Date"]).reset_index(drop=True)

### Check data

In [ ]:
stock_df.head()

  Company       Date    Close     Volume     Open     High      Low
0    AAPL 2013-07-18  15.4199  218632537  15.4779  15.5311  15.3789
1    AAPL 2013-07-19  15.1768  268548901  15.4679  15.4993  15.1554
2    AAPL 2013-07-22  15.2254  207648981  15.3379  15.3482  15.1953
3    AAPL 2013-07-23  14.9639  354477618  15.2143  15.2486  14.9539
4    AAPL 2013-07-24  15.7325  591624923  15.6761  15.8782  15.5450

In [ ]:
stock_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25160 entries, 0 to 25159
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Company  25160 non-null  object
 1   Date     25160 non-null  datetime64[ns]
 2   Close    25160 non-null  float64
 3   Volume   25160 non-null  int64
 4   Open     25160 non-null  float64
 5   High     25160 non-null  float64
 6   Low      25160 non-null  float64
dtypes: datetime64[ns](1), float64(4), int64(1), object(1)
memory usage: 1.3+ MB

In [ ]:
stock_df.describe()

,Date,Close,Volume,Open,High,Low
count,25160,25160.000000,2.516000e+04,25160.000000,25160.000000,25160.000000
mean,2018-07-15 16:11:49.697933056,102.455878,5.131764e+07,102.430761,103.829305,101.006112
min,2013-07-18 00:00:00,1.620000,1.143952e+06,1.620000,1.690000,1.610000
25%,2016-01-14 18:00:00,36.567500,1.200394e+07,36.507500,36.890000,36.128000
50%,2018-07-16 12:00:00,65.680000,2.672083e+07,65.650000,66.486900,64.915500
75%,2021-01-13 06:00:00,134.235025,6.857269e+07,134.320000,136.233525,132.660000
max,2023-07-17 00:00:00,691.690000,1.065209e+09,692.350000,700.989400,686.090000
std,NaN,101.991372,6.399143e+07,101.996115,103.529523,100.399743

## Save cleaned data

In [ ]:
stock_df.to_csv('/content/stock_cleaned.csv')